version: '3'
services:
   peer1:
      build: ./blockchain/
      ports:
         - 10006:5000
      environment:
         - PEER_PORT=10006
         - PEER1=peer2:10007
         - PEER2=peer3:10008
         - PEER3=peer4:10009
   peer2:
      build: ./blockchain/
      ports:
         - 10007:5000
      environment:
         - PEER_PORT=10007
         - PEER1=peer1:10006
         - PEER2=peer3:10008
         - PEER3=peer4:10009
   peer3:
      build: ./blockchain/
      ports:
         - 10008:5000
      environment:
         - PEER_PORT=10008
         - PEER1=peer1:10006
         - PEER2=peer2:10007
         - PEER3=peer4:10009

   peer4:
      build: ./blockchain/
      ports:
         - 10009:5000
      environment:
         - PEER_PORT=10009
         - PEER1=peer1:10006
         - PEER2=peer2:10007
         - PEER3=peer3:10008