version: '3'
services:
   peer1:
      build: ./blockchain/
      ports:
         - 10006:5000
      environment:
         - PYTHONUNBUFFERED=0
         - PEER1=peer2
         - PEER2=peer3
         - PEER3=peer4
   peer2:
      build: ./blockchain/
      ports:
         - 10007:5000
      environment:
         - PYTHONUNBUFFERED=0
         - PEER1=peer1
         - PEER2=peer3
         - PEER3=peer4
   peer3:
      build: ./blockchain/
      ports:
         - 10008:5000
      environment:
         - PYTHONUNBUFFERED=0
         - PEER1=peer1
         - PEER2=peer2
         - PEER3=peer4

   peer4:
      build: ./blockchain/
      ports:
         - 10009:5000
      environment:
         - PYTHONUNBUFFERED=0
         - PEER1=peer1
         - PEER2=peer2
         - PEER3=peer3