Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "forwarded_port", guest: 80, host: 3000
  config.vm.synced_folder "../", "/synced_folder"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "si_blockchain"
    vb.memory = "2048"
    vb.cpus = "2"
  
  config.vm.provision :docker
  config.vm.provision :docker_compose
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update
  SHELL
end