Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 10006, host: 10006
  config.vm.network "forwarded_port", guest: 10007, host: 10007
  config.vm.network "forwarded_port", guest: 10008, host: 10008
  config.vm.network "forwarded_port", guest: 10009, host: 10009
  config.vm.synced_folder "../", "/synced_folder"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "si_blockchain"
    vb.memory = "4096"
    vb.cpus = "2"
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
	sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	wait
	sudo add-apt-repository \
		"deb [arch=amd64] https://download.docker.com/linux/ubuntu \
		$(lsb_release -cs) \
			stable"
	
	sudo apt-get update		
	sudo apt-get install -y docker-ce
	sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
	sudo chmod +x /usr/local/bin/docker-compose
  SHELL
end